Add Chinese Translations for Alda Documention
alda-lang/alda pull request #502
Opened 2024-09-02 12:26 UTC by OWALabuy

**Description:**
This PR adds Chinese translations for four Alda documentation pages to increase accessibility for Chinese-speaking users. The translated documents are located in the `doc/doc_zh_cn` directory.

### Summary of Changes:
- Translated the following documents into Chinese:
  1. index.md
  2. notes.md
  3. tempo.md
  4. editor-plugins.md

### Motivation:
With this translation, Alda will be more accessible to a wider audience, potentially growing the user base and community. These translations are a first step, and I plan to continue translating more documentation.

### Notes:
- Let me know if there are any specific changes or adjustments needed for these translations.
- I’m open to feedback and willing to make any necessary revisions.

2024-09-03 21:16 UTC, daveyarwood commented on doc/doc_zh_cn/chords_zh_cn.md
> +*此页面翻译自[chouds.md](../chouds.md)*
Possible typo?

2024-09-03 21:18 UTC, daveyarwood commented on doc/tempo.md
> +"pulse" to stay the same, but now each beat is subdivided into 4 eighth notes
Good catch!

2024-09-03 21:20 UTC, daveyarwood commented on player/gradle/wrapper/gradle-wrapper.properties
> +zipStoreBase=GRADLE_USER_HOME
Can we revert the changes to this file, since they aren't needed?

2024-09-03 23:00 UTC, daveyarwood requested changes
Looks great, thanks so much for doing this!

2024-09-04 00:37 UTC, OWALabuy commented on doc/doc_zh_cn/chords_zh_cn.md
> +*此页面翻译自[chouds.md](../chouds.md)*
sorry... I will correct it

2024-09-24 05:20 UTC, cewno requested changes

2024-09-24 05:20 UTC, cewno commented on doc/doc_zh_cn/alda-2-migration-guide_zh_cn.md
> +我们希望您喜欢 Alda 2！请随时加入我们的 [Slack 群组][alda-slack] 并让我们知道您的想法。如果你遇到 bug 或任何其他类型的奇怪行为，你也可以 [开issue][open-an-issue]，我们很乐意帮助您解决问题！
`开 issue` 多用于日常交流中，在文档等较为正式语境下用`打开一个 issue`更好，且方便不熟悉开源社区的人使用

2024-09-24 05:20 UTC, cewno commented on doc/doc_zh_cn/alda-2-migration-guide_zh_cn.md
> +>>>>>>> 49cbb58fe0457925da96f47923b0833ea92a72b6
这里是不是没处理好冲突

2024-09-28 20:53 UTC, daveyarwood approved these changes
@OWALabuy @cewno This is awesome! Thanks so much for your hard work on this.

2024-09-28 20:53 UTC, merged